from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


def _slugify(value: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9]+", "_", value.strip())
    return cleaned.strip("_").lower() or "sims4_mod"


@dataclass(frozen=True)
class ProjectContext:
    project_name: str
    creator: str
    module_name: str


def _project_files(context: ProjectContext) -> dict[str, str]:
    return {
        "README.md": f"""# {context.project_name}

Generated by `sims4-stark-devkit`.

## Layout

- `src/{context.module_name}/main.py` - startup hook
- `src/{context.module_name}/modinfo.py` - mod metadata
- `tests/` - lightweight compatibility tests

## Recommended workflow

1. Edit your source under `src/{context.module_name}`.
2. Run `stark-devkit test .` often.
3. Build your `.ts4script` with your preferred compiler or packaging step.
4. Keep the final archive at the top level or one folder deep inside the Sims 4 Mods folder.
""",
        "pyproject.toml": f"""[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{context.module_name.replace('_', '-')}"
version = "0.1.0"
description = "{context.project_name} Sims 4 mod"
readme = "README.md"
requires-python = ">=3.12"
authors = [{{name = "{context.creator}"}}]

[tool.setuptools]
package-dir = {{"": "src"}}

[tool.setuptools.packages.find]
where = ["src"]
""",
        f"src/{context.module_name}/__init__.py": "\"\"\"Sims 4 mod package.\"\"\"\n",
        f"src/{context.module_name}/modinfo.py": f'''from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ModInfo:
    name: str = "{context.project_name}"
    creator: str = "{context.creator}"
    namespace: str = "{context.module_name}"
    version: str = "0.1.0"


MOD_INFO = ModInfo()
''',
        f"src/{context.module_name}/main.py": f'''from __future__ import annotations

from .modinfo import MOD_INFO


def on_load() -> str:
    """Simple load hook placeholder."""
    return f"{{MOD_INFO.name}} by {{MOD_INFO.creator}} loaded"
''',
        "tests/test_project_shape.py": f'''from __future__ import annotations

import importlib
import unittest


class ProjectShapeTests(unittest.TestCase):
    def test_modinfo_imports(self) -> None:
        mod = importlib.import_module("{context.module_name}.modinfo")
        self.assertEqual(mod.MOD_INFO.namespace, "{context.module_name}")


if __name__ == "__main__":
    unittest.main()
''',
        ".gitignore": "__pycache__/\n*.pyc\nbuild/\ndist/\n",
    }


def init_project(destination: str | Path, *, name: str, creator: str, module_name: str | None = None) -> Path:
    project_dir = Path(destination).resolve()
    context = ProjectContext(
        project_name=name,
        creator=creator,
        module_name=module_name or _slugify(name),
    )

    for relative_path, contents in _project_files(context).items():
        target = project_dir / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(contents, encoding="utf-8")

    return project_dir

